pipeline {
    agent any
    
    tools{
        maven "MAVEN"
    }

    stages {
	
		stage("Checkout code"){
			steps
			{
				checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: '31782584-e788-4f38-bf61-e7dba9f375ec', url: 'https://git.nagarro.com/GITG00641/Java/raj-raushan.git']]])
				echo 'Check Out'
			}
        }
        stage('Clean') {
            steps {
                bat 'mvn -f AdvancedJavaAssignment5/ManageLibraryBoot/pom.xml clean'
                echo 'Cleaning..'
            }
        }
        stage('Compile') {
            steps {
                bat 'mvn -f AdvancedJavaAssignment5/ManageLibraryBoot/pom.xml compile'
                echo 'Compiling..'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn -f AdvancedJavaAssignment5/ManageLibraryBoot/pom.xml test'
                echo 'Testing..'
            }
        }
        stage('Packaging') {
            steps {
                bat 'mvn -f AdvancedJavaAssignment5/ManageLibraryBoot/pom.xml package'
                echo 'Packageing..'
            }
        }
        stage('Install') {
            steps {
                bat 'mvn -f AdvancedJavaAssignment5/ManageLibraryBoot/pom.xml install'
                echo 'Installing..'
            }
        }
        
      
    }
}
